CREATE TABLE dbo.Jobs (
    Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Scheduled_Time DATETIME NOT NULL,
    Start_Time DATETIME NULL,
    EndTime DATETIME NULL,
    Success BIT NOT NULL DEFAULT(0),
    Status TINYINT NOT NULL DEFAULT(0)
)